ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: 'true'
  hosts: [staging.neu.ro]

sentry:
  dsn: https://80b17e5f9cae4243a4a8b791e6481c9a@o489136.ingest.sentry.io/5553359
  clusterName: staging
  sampleRate: 0.002

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platformneuroflowapi-postgres
        key: platformneuroflowapi-service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: postgres
        key: admin-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platformneuroflowapi-postgres
        key: platformneuroflowapi-migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platformneuroflowapi-postgres
        key: platformneuroflowapi-service-dsn

  migrations:
    env:
      - name: NP_DB_POSTGRES_DSN
        valueFrom:
          secretKeyRef:
            name: platformneuroflowapi-postgres
            key: platformneuroflowapi-migrations-dsn

corsOrigins: https://neu.ro,https://app.neu.ro
