apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformNeuroFlow.fullname" . }}
  labels: {{ include "platformNeuroFlow.labels.standard" . | nindent 4 }}
    service: platform-neuro-flow
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_NEURO_FLOW_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    app: {{ include "platformNeuroFlow.name" . }}
    release: {{ .Release.Name }}
    service: platform-neuro-flow
---
# TODO: Old service definition. Check that it is not used elsewhere and remove.
apiVersion: v1
kind: Service
metadata:
  name: platformneuroflowapi
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_NEURO_FLOW_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    app: {{ include "platformNeuroFlow.name" . }}
    release: {{ .Release.Name }}
    service: platform-neuro-flow
