apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformneuroflowapi
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: platformneuroflowapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformneuroflowapi
    spec:
      containers:
      - name: platformneuroflowapi
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.command }}
        command: {{ toYaml .Values.command | nindent 8 }}
        {{- end }}
        {{- if .Values.args }}
        args: {{ toYaml .Values.args | nindent 8 }}
        {{- end }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: {{ .Values.port }}
            name: tcp-web
            protocol: TCP
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        env:
        - name: NP_NEURO_FLOW_API_PORT
          value: {{ .Values.port | quote }}
        - name: NP_NEURO_FLOW_API_PLATFORM_AUTH_URL
          value: {{ .Values.authUrl }}
        - name: NP_NEURO_FLOW_API_PLATFORM_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}
        - name: NP_CORS_ORIGINS
          value: {{ .Values.corsOrigins }}
        {{- if .Values.sentry.url }}
        - name: NP_SENTRY_URL
          value: {{ .Values.sentry.url }}
        {{- end }}
        {{- if .Values.sentry.cluster }}
        - name: NP_SENTRY_CLUSTER
          value: {{ .Values.sentry.cluster }}
        {{- end }}
        {{- if .Values.enableDocs }}
        - name: NP_NEURO_FLOW_API_ENABLE_DOCS
          value: "true"
        {{- end }}
{{- if .Values.postgres.dsn }}
        - name: NP_DB_POSTGRES_DSN
{{ toYaml .Values.postgres.dsn | indent 10 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: platformneuroflowapi
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_NEURO_FLOW_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    service: platformneuroflowapi
