{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: platformneuroflowapi
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-trust-headers: "true"
    ingress.kubernetes.io/auth-url: {{ .Values.platformIngressAuthUrl }}/oauth/authorize
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1/flow/
        backend:
          serviceName: platformneuroflowapi
          servicePort: http
  {{- end }}
{{- end }}
