image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG
imagePullSecrets: []

command: []
args: []

port: 8080

replicas: 2

resources:
  requests:
    cpu: '0.1'
    memory: 300Mi
  limits:
    cpu: '0.2'
    memory: 600Mi

ingress:
  enabled: false

postgres-db-init:
  adminDsn: {}
  migrationsRunnerDsn: {}
  serviceDsn: {}

  migrations:
    enabled: true

    image:
      repository: "$IMAGE_REPO"
      tag: "$IMAGE_TAG"

    command: ["alembic", "upgrade", "head"]

secrets: []

sentry: {}

platform:
  authUrl: http://platform-auth:8080
  apiUrl: http://platform-api:8080
  token: {}

postgres:
  dsn: {}

enableDocs: false

priorityClassName: ""

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
