image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG
imagePullSecrets: []

command: []
args: []

port: 8080

replicas: 2

resources:
  requests:
    cpu: '0.1'
    memory: 300Mi
  limits:
    cpu: '0.2'
    memory: 600Mi

service:
  labels: {}
  annotations: {}

ingress:
  enabled: false

  hosts: []

  className: ""

  labels: {}
  annotations: {}

postgres-db-init:
  adminDsn: {}
  migrationsRunnerDsn: {}
  serviceDsn: {}

  migrations:
    enabled: true

    image:
      repository: "$IMAGE_REPO"
      tag: "$IMAGE_TAG"

    command: ["alembic", "upgrade", "head"]

secrets: []

externalSecrets: []
#   - name: platform-admin-secret
#     secretStoreName: vault-backend
#     secretStoreKind: ClusterSecretStore
#     data:
#       DATABASE_URL:
#         key: kv-v2/platform
#         property: DATABASE_URL
#       API_KEY:
#         key: kv-v2/platform
#         property: API_KEY

sentry: {}

platform:
  authUrl: http://platform-auth:8080
  apiUrl: http://platform-api:8080
  eventsUrl: http://platform-events:8080/apis/events
  token: {}

postgres:
  dsn: {}

enableDocs: false

priorityClassName: ""

securityContext:
  enabled: false
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
