ingress:
  enabled: true
  hosts: [dev.neu.ro]

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002

platform:
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

postgres:
  dsn:
    valueFrom:
      secretKeyRef:
        name: platform-neuro-flow-postgres
        key: service-dsn

postgres-db-init:
  adminDsn:
    valueFrom:
      secretKeyRef:
        name: platform-postgresql
        key: postgresql-dsn
  migrationsRunnerDsn:
    valueFrom:
      secretKeyRef:
        name: platform-neuro-flow-postgres
        key: migrations-dsn
  serviceDsn:
    valueFrom:
      secretKeyRef:
        name: platform-neuro-flow-postgres
        key: service-dsn
  migrations:
    env:
    - name: NP_DB_POSTGRES_DSN
      valueFrom:
        secretKeyRef:
          name: platform-neuro-flow-postgres
          key: migrations-dsn


cors:
  origins:
  - '*'

enableDocs: true

priorityClassName: "platform-services"
